INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name1', 'myemail1@unknown.com', 30, '2000-01-31', 'M');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name2', 'myemail2@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name3', 'myemail3@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name4', 'myemail4@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name5', 'myemail5@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name6', 'myemail6@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name7', 'myemail7@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name8', 'myemail8@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name9', 'myemail9@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name10', 'myemail10@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name11', 'myemail11@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name12', 'myemail12@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name13', 'myemail13@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name14', 'myemail14@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name15', 'myemail15@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name16', 'myemail16@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name17', 'myemail17@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name18', 'myemail18@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name19', 'myemai19@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name20', 'myemai20@unknown.com', 10, '2020-02-01', 'F');

INSERT INTO ZZZ_CRUD
(USER_NM, USER_EMAIL, USER_AGE, USER_BIRTH, USER_GENDER)
VALUES
('my_name21', 'myemail21@unknown.com', 10, '2020-02-01', 'F');